### PR TITLE
Added new MPC files (trial sequences in blocks, reduced feature-target gap, red light off during feature, pure tone changed to clicker, features presented via left & right panel lights)

### PR DESCRIPTION
**Pull request by rhuszar**
**Description**:
The pull request comprises 2 new files added to the 'experimental_control' folder. The added files are updated MPC files for running behavior in the biconditional discrimination task. Compared to the previous files used, the new files include the following changes:
- Trial sequences are presented in blocks of 4 trials of the same type (4 trial types in total, got two blocks of each per sequence, so 32 trials per trial sequence overall) - 24 unique and "different enough" (using edit distance of 4 - see https://en.wikipedia.org/wiki/Edit_distance) sequences were generated and used to produce 50 sequences (_note_: each sequence appears at least twice - once in the first 24, and and then in the next 24 sequences), such that 3 sequences starting with a rewarded block are always followed by 2 sequences starting with a non rewarded block. MATLAB file (controlBlocks.m) that generated the sequences is here: https://github.com/rhuszar/rh_bicondCode
- The gap between the feature (light) cue and target (tone) cue was reduced from 5seconds to 1second.
- Red background light gets turned off during presentations of the light cues.
- The pure tone was changed to 10Hz click - the target (tone) cues are therefore a white noise and a click.
- Steady light is now presented via the left panel light, and the flashing light is presented via the right panel light.

**How has this been tested?**
A test session has been run on the MedPC boxes to ensure that all changes are in place. 

**How long should this take to review**?
Short

**Types of changes**:
Changed feature.

### CODE REVIEW

**Comment by emirvine** [comment]
Could you expand your commit message? Since we're uploading a new file here instead of modifying the existing one, it'd be good to have a more detailed explanation in the commit of what exactly was modified for this experiment compared to the last experiment. 

And it's fine for now, but in the future it'd be nice to have a description included in the pull request so that I have some idea of how much time it'll take to review this request. Examples can be found the pull requests in the python-vdmlab repository (https://github.com/vandermeerlab/python-vdmlab/pulls?q=is%3Apr+is%3Aclosed).

**Comment by mvdm** [comment]
it would also be useful to link to the (MATLAB?) file that generated the sequences

**Comment by emirvine** [comment]
Thanks for updating the PR description, looks good! Could you copy most of that text to the commit message though? This would require amending the commit you've already made -- see https://help.github.com/articles/changing-a-commit-message/ for a guide. And make sure your commit message fits the template: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html (or http://chris.beams.io/posts/git-commit/)

**Comment by rhuszar** [comment]
I updated my comment above to include a link to the MATLAB files I made to generate the sequences. I also amended the commit message, and force pushed. Let me know if you have more thoughts/tips!

**Comment by emirvine** [comment]
Merged this in c7a123b580b1cd355dbc46f947b6bba12ceee76a. Github didn't mark it as merged because I amended your commit to fit the commit message template (http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html). In the future, make sure your first line is closer to 50 characters and you add in line breaks around 72 characters for the "body" and an empty line in between every bullet.

**Pull request closed without merging**
